site_name: Flight Deck Documentation

repo_url: https://github.com/ten7/flight-deck
site_description: 'Flight Deck â€“ Dockerize your Drupal development'
theme: readthedocs

markdown_extensions:
  - toc:
      permalink: True

pages:
  - Introduction: 'index.md'
  - Getting started: 'gettingStarted.md'
  - Creating a URL alias: 'urlAlias.md'
  - Xdebug: 'xdebug/index.md'
